[versions]
reproducible-builds = "1.1"
spotless = "8.1.0"

[libraries]
spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
plugin-publish = { module = "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin", version = "2.0.0"}
kotlin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version = "2.3.0" }
nebula-apache-license = { module = "com.netflix.nebula.maven-apache-license:com.netflix.nebula.maven-apache-license.gradle.plugin", version = "23.0.0"}
reproducible-builds = { module = "org.gradlex.reproducible-builds:org.gradlex.reproducible-builds.gradle.plugin", version.ref = "reproducible-builds" }
sigstore = { module = "dev.sigstore.sign:dev.sigstore.sign.gradle.plugin", version = "2.0.0" }

[plugins]
reproducible-builds = { id = "org.gradlex.reproducible-builds", version.ref = "reproducible-builds" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
